### PR TITLE
Add named-readtables support

### PR DESCRIPTION
**Pull request by daewok**

### CODE REVIEW

**Comment by mmontone** [comment]
Thanks!

How do reader syntax work after this change. How do you enable the #v syntax. 

enable-version-syntax continues working after this? 

Should we add a comment on that to README?

**Comment by daewok** [comment]
enable-version-syntax still works, I didn't want to break any existing code! But [named-readtables](https://github.com/melisgl/named-readtables) is a pretty commonly used way to manage readtables, so I thought it would be nice to have support for it as well.

You can use the #v syntax by adding:

```lisp
(named-readtables:in-readtable cl-semver:semver-syntax)
```

to a source file. I added a bit to the README, but I guess it already requires familiarity with named-readtables to understand how to use it! I can expand a bit if you want.

**Comment by mmontone** [comment]
I would just add this to the README in the named-readtables section:

```
You can use the #v syntax by adding:

(named-readtables:in-readtable cl-semver:semver-syntax)
```

can you do that?

**Comment by daewok** [comment]
Sorry, had to step away for a bit. Your addition looks great to me!

**Comment by mmontone** [comment]
Thank you for your contributions!

**Pull request merged**
